openapi: 3.0.0
info:
  title: muffins
  version: '1.0'
  description: API для интеграции приложения для розничных покупателей и базы 1С
servers:
  - url: 'https://link.muffinsbakery.ru:7143/unf-201908/hs/api/v1/pvt'
paths:
  /delivery:
    get:
      summary: Доставка
      tags:
        - Методы
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Delivery.v1.yaml
      operationId: get-delivery
      description: Цена доставки - КАД/за КАДом
  /menu:
    get:
      summary: Меню
      tags:
        - Методы
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Category.v1.yaml
      operationId: get-menu
      description: Меню в разрезе категорий
      parameters: []
  /order:
    post:
      summary: Заказ
      operationId: post-order
      responses:
        '200':
          description: OK
      description: Отправка заказа
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Order.v1.yaml
      tags:
        - Методы
  /promos:
    get:
      summary: Акции
      tags:
        - Методы
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Promo.v1.yaml
      operationId: get-promos
      description: Получение акций и промокодов
    parameters: []
  /upsale:
    get:
      summary: Подарок при покупке
      tags:
        - Методы
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Item.v1.yaml
      operationId: get-upsale
      description: Бонусы к покупке
  /promocodes:
    get:
      summary: Получение промокодов
      tags:
        - Методы
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/PromoCode.v1.yaml
      operationId: get-promocodes
      description: Получение промокодов
components:
  schemas: {}
  securitySchemes:
    insert here:
      type: http
      scheme: bearer
security:
  - insert here: []
tags:
  - name: Методы
